# Generated by Django 3.0.8 on 2020-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('active', models.IntegerField()),
                ('inActive', models.IntegerField()),
                ('maxAactive', models.IntegerField()),
                ('count', models.IntegerField()),
                ('errors', models.IntegerField()),
                ('timeOuts', models.IntegerField()),
                ('latency', models.IntegerField()),
                ('peakLatency', models.IntegerField()),
                ('throughPut', models.TextField()),
            ],
        ),
    ]
