# Generated by Django 3.0.8 on 2020-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statreports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrow',
            name='id',
        ),
        migrations.AlterField(
            model_name='reportrow',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
