version: '3.7'

services:
    # db:
    #   image: postgres
    #   environment:
    #     - POSTGRES_DB=postgres
    #     - POSTGRES_USER=postgres
    #     - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: /usr/local/bin/gunicorn django_project.wsgi:application -w 2 -b :8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      # depends_on:
      #   - db
